# Permalinks
permalink:           pretty

# Setup
title:               My Digital World
tagline:             my musings
url:                 http://av1na5h.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Avinash 
  url:               https://twitter.com/av1n45h
  email:             tba

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/av1n45h

# Gems
#gems:
#  - jekyll-paginate

#for navigation bar
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'